{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gatemux.serviceAccountName" . }}
  labels:
    {{- include "gatemux.labels" . | nindent 4 }}
{{- end -}}
